{{- if .Values.deployments.dlstreamer.configuration.chart.auth.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.deployments.dlstreamer.configuration.chart.auth.secret.name }}
  namespace: {{ .Values.Block.InstanceId }}
type: Opaque
stringData:
  {{ .Values.deployments.dlstreamer.configuration.chart.auth.secret.key }}: {{ .Values.deployments.dlstreamer.configuration.chart.auth.password | toYaml }}

{{- end }}
